CC=gcc
CPP=g++
# g++ spiralorder.cpp -o spiralorder  -std=c++0x.
# g++ wordbreak.cpp -o wordbreak  -std=c++0x
# g++ findladders_2.cpp  -std=c++0x
#SRC=findladders.cpp
#SRC=insertsort.cpp
#SRC=mergetwolists.cpp
#SRC=removedup2.cpp
#SRC=singlenum2.cpp
#SRC=maxdepth.cpp
#SRC=issametree.cpp
#SRC= reverse.cpp
#SRC=maxprofit.cpp
#SRC=maxprofit_ii.cpp
#SRC=numtree.cpp
#SRC=hascycle.cpp
#SRC= preorder.cpp
#SRC=preorder2.cpp
#SRC=connect.cpp
#SRC=searchinsert.cpp
#SRC=deletedupnode.cpp
#SRC=romontoint.cpp
#SRC=climbstairs.cpp
#SRC=singlenumberii.cpp
#SRC=maxsubarray.cpp
#SRC=int2roman.cpp
#SRC=int2roman_2.cpp
#SRC=removeelement.cpp
#SRC= solvenqueens.cpp
#SRC=solvenqueens_dfs.cpp
#SRC=totalnqueens.cpp
#SRC=isbalanced.cpp
#SRC=swappairs.cpp
#SRC= sortedarraytobst.cpp
#SRC= mergeSortedArray.cpp
#SRC= mergeSortedArray2.cpp
#SRC= graycode.cpp
#SRC= issymmetric.cpp
#SRC= issymmetric_iterate.cpp
#SRC= sortcolors.cpp
#SRC= pascalTriangle.cpp
#SRC= permutations.cpp
#SRC= plusOne.cpp
#SRC= generateParenthesis.cpp
#SRC= uniquePaths.cpp
#SRC= levelOrderBottome.cpp
#SRC= minPathSum.cpp
#SRC= containerWithMostWater_2.cpp
#SRC= postorderTraversal.cpp
#SRC= detectCycle.cpp
#SRC= detectCycle_2.cpp
#SRC= levelOrder.cpp
#SRC= setZeros.cpp
#SRC= spiralMatrixII.cpp
#SRC= searchInRotatedSortedArray.cpp
#SRC= searchInRotatedSortedArray_bs2.cpp
#SRC= searchInRotatedSortedArray_bs2.cpp
#SRC= searchInRotatedSortedArrayII.cpp
#SRC= deleteDuplicates.cpp
#SRC= removedup2.cpp
#SRC= hasPathSum.cpp
#SRC= hasPathSum2.cpp
#SRC= getRow.cpp
#SRC= connectII.cpp
#SRC= combine.cpp
#SRC= removeNthFromEnd.cpp
#SRC= removeNthFromEnd_2.cpp
#SRC= sumNumbers.cpp
#SRC= sumNumbers_stack.cpp
#SRC= minDepth.cpp
#SRC= lengthOfLastWord.cpp
#SRC= trapping_2.cpp
#SRC= flatten.cpp
#SRC= logestConsecutive.cpp
#SRC= uniquePathsWithObstacles.cpp
#SRC= isValidSudoku.cpp
#SRC= subset.cpp
#SRC= subset_2.cpp
#SRC= searchRange.cpp
#SRC= sortedListToBST.cpp
#SRC= sortedListToBST.cpp
#SRC= generateTrees_dp.cpp
#SRC= generateTrees_dp2.cpp
#SRC= countAndSay.cpp
#SRC= longestcommonprefix.cpp
#SRC= canJump.cpp
#SRC= subsetsWithDup.cpp
#SRC= pathSum.cpp
#SRC= partition.cpp
SRC= triangle.cpp
SRC= permuteUnique.cpp
SRC= next_permute.cpp
SRC= buildTree.cpp
SRC= buildTree_from_postorder.cpp
SRC= buildTree_from_postorder_stack.cpp
SRC= zigzag_level_order.cpp
SRC= letterCombinations.cpp
SRC= reverseBetween.cpp
SRC= palindrome_parition.cpp
SRC= pow.cpp
SRC= is_valid_bst.cpp
SRC= add_binary.cpp
SRC= add_binary_improved.cpp
SRC= find_minimum.cpp
SRC= find_minimum_bs.cpp
SRC= find_minimum_dup.cpp
SRC= min_distance.cpp
SRC= next_permutation.cpp
SRC= reverseKGroup.cpp
SRC= preorder_zyj.cpp
SRC= numdistinct.cpp
SRC= jumpii.cpp
SRC= combinationsum2.cpp
SRC= recover_tree.cpp
SRC= zigzag_convert.cpp
SRC= copy_random_list.cpp
SRC= clone_graph.cpp
SRC= add_two_numbers.cpp
SRC= preorder_morrist.cpp
SRC= permutation_seq.cpp
SRC= word_search.cpp
SRC= word_break_ii.cpp
SRC= restore_ip_address.cpp
SRC= solve_sudoku.cpp
SRC= regex.cpp
SRC= wildcard_match.cpp
SRC= wildcard_match_iterate.cpp
SRC= merge_intervals.cpp
SRC= insert_interval.cpp
SRC= min_stack.cpp
SRC= min_stack_stack.cpp
SRC= merge_k_lists.cpp
SRC= find_median_sorted_arrays.cpp
SRC= firstMissingPositive.cpp
SRC= largest_rectangle_area.cpp
SRC= largest_rectangle_area_opt.cpp
SRC= maxmimal_rectangle.cpp
SRC= buy_and_sell_stockIII.cpp
SRC= three_sum.cpp
SRC= three_sum_doublepoints.cpp
SRC= 4sum.cpp
SRC= scramble_string.cpp
SRC= scramble_string_dp.cpp
SRC= sqrt.cpp
SRC= logest_substr_without_repeat_charater.cpp
SRC= rotate_list.cpp
SRC= is_palindrome.cpp
SRC= strStr.cpp
SRC= longestPalindrome.cpp
SRC= find_peak_element.cpp
SRC= intersection_of_two_linked_lists.cpp
SRC= binary_tree_maximum_path_sum.cpp
SRC= strStr_kmp.cpp
SRC=strStr_bm.cpp
SRC= multiply_string.cpp
SRC=maximum_gap.cpp
SRC=maximum_gap_bucket_sort.cpp
SRC=compare_version_numbers.cpp
SRC=fraction_to_reccurring_decimal.cpp
SRC=excel_sheet_column_title.cpp
SRC=majority_element_bitmanipulation.cpp
SRC=recorder_list.cpp
SRC=evalRPN.cpp
SRC= longest_valid_parentheses.cpp
SRC= logest_valid_parentheses_stack.cpp
SRC= simplify_path.cpp
SRC= minimum_window_substring.cpp
SRC= excel_sheet_column_number.cpp
SRC= factorial_trailing_zeroes.cpp
SRC= candy.cpp
SRC= candy_twopass.cpp
SRC= binary_search_tree_iterator.cpp
SRC= palindrome_partitioningII.cpp
SRC= lru_cache.cpp
SRC= surrounded_regions.cpp
SRC= surrounded_regions_bfs.cpp
SRC= word_ladder.cpp
SRC= word_ladder_opt.cpp
SRC= substring_with_concatenation_of_all_words.cpp
SRC= text_justification.cpp
SRC= multiply_string.cpp
SRC= valid_number.cpp
SRC= valid_number_dfa.cpp
SRC= strStr_cleancode.cpp
SRC= media_of_two_sorted_array.cpp
SRC= media_of_two_sorted_array_2nd.cpp
SRC= reverse_words_in_a_string.cpp
SRC= reverse_words_in_a_string_inplace.cpp
SRC= string_to_integer_cleancode.cpp
SRC= valid_number_cleancode.cpp
SRC= strStr_rabin_carp.cpp
SRC= longest_substr_without_repeat_character.cpp
SRC= longest_substr_without_repeat_character_cleancode.cpp
SRC= longest_palindrome_cleancode.cpp
SRC= reverse_integer.cpp
SRC= palindrome_number_cleancode.cpp
SRC= swap_nodes_in_pairs.cpp
SRC= merge_k_lists.cpp
SRC= merge_k_sorted_lists_cleancode.c
SRC= range_sum_query_mutable.c
SRC= additive_number.c
SRC= minimum_height_trees.c
SRC= 309_sell_stock.c
SRC= 316_remove_duplicate_letters.c

CFLAG=-Wimplicit-function-declaration

# all: $(SRC)
#    $(CPP) $(SRC) -o a  -std=c++0x -g
all: $(SRC)
	$(CC) $(CFLAG) $(SRC) -o a -g



